# Generated by Django 5.0.1 on 2025-10-26 11:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='Từ khóa tìm kiếm')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian tìm kiếm')),
                ('total_results', models.IntegerField(default=0, verbose_name='Tổng số kết quả')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Thông báo lỗi')),
            ],
            options={
                'verbose_name': 'Truy vấn tìm kiếm',
                'verbose_name_plural': 'Truy vấn tìm kiếm',
                'db_table': 'search_queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Tên doanh nghiệp')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Đánh giá')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Số lượng đánh giá')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Danh mục')),
                ('google_maps_url', models.URLField(blank=True, null=True, verbose_name='Link Google Maps')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Kinh độ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='business_scraper.searchquery', verbose_name='Truy vấn tìm kiếm')),
            ],
            options={
                'verbose_name': 'Doanh nghiệp',
                'verbose_name_plural': 'Doanh nghiệp',
                'db_table': 'businesses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='businesses_name_fa0a0c_idx'), models.Index(fields=['phone'], name='businesses_phone_c3daea_idx'), models.Index(fields=['email'], name='businesses_email_ac7bcc_idx'), models.Index(fields=['-created_at'], name='businesses_created_eca15e_idx')],
            },
        ),
    ]
