# Generated by Django 5.0.1 on 2025-10-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link Google Maps'),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Website'),
        ),
    ]
