# Generated by Django 5.0.1 on 2025-10-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_scraper', '0002_alter_business_google_maps_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='source',
            field=models.CharField(choices=[('google_maps', 'Google Maps'), ('duckduckgo', 'DuckDuckGo')], default='google_maps', max_length=20, verbose_name='Nguồn'),
        ),
    ]
