# Generated by Django 5.0.1 on 2025-10-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_scraper', '0003_business_description_searchquery_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='source',
            field=models.CharField(choices=[('google_maps', 'Google Maps'), ('duckduckgo', 'DuckDuckGo'), ('hsctvn', 'HSCTVN')], default='google_maps', max_length=20, verbose_name='Nguồn'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['tax_id'], name='businesses_tax_id_a4a32e_idx'),
        ),
    ]
