# Generated by Django 5.0.1 on 2025-10-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_scraper', '0004_business_tax_id_alter_searchquery_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cấp'),
        ),
        migrations.AddField(
            model_name='business',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Đại diện pháp luật'),
        ),
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Trạng thái'),
        ),
    ]
